In [247]:
import os
import numpy as np 
import pandas as pd

In [248]:
df=pd.read_csv(r"C:\Users\abc\OneDrive\self_practice\medical_disease_prediction_10000.csv")

In [249]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,Male,17.5,102,177,161,88,No,No,Medium,No,Healthy
1,69,Male,31.1,118,256,147,92,No,No,High,Yes,Pre-Diabetes
2,61,Female,31.3,114,206,193,74,Yes,No,Medium,No,Healthy
3,47,Female,23.9,105,162,253,68,No,No,Low,No,Healthy
4,47,Male,28.3,148,121,280,84,No,Yes,High,No,Healthy
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,Male,27.1,177,183,268,59,No,No,High,No,Hypertension
9996,84,Male,29.2,142,215,145,77,No,Yes,High,Yes,Hypertension
9997,41,Male,22.8,177,265,133,71,No,No,Medium,Yes,Hypertension
9998,55,Male,29.0,126,241,298,57,No,No,Medium,Yes,Pre-Diabetes
9999,59,Male,32.2,151,162,225,93,No,No,High,Yes,Pre-Diabetes

In [250]:
df['Disease']

0            Healthy
1       Pre-Diabetes
2            Healthy
3            Healthy
4            Healthy
            ...
9995    Hypertension
9996    Hypertension
9997    Hypertension
9998    Pre-Diabetes
9999    Pre-Diabetes
Name: Disease, Length: 10000, dtype: str

In [251]:
df['PhysicalActivity']

0       Medium
1         High
2       Medium
3          Low
4         High
         ...
9995      High
9996      High
9997    Medium
9998    Medium
9999      High
Name: PhysicalActivity, Length: 10000, dtype: str

In [252]:
df['PhysicalActivity'].unique()

<StringArray>
['Medium', 'High', 'Low']
Length: 3, dtype: str

In [253]:
df['Disease'].unique()

<StringArray>
['Healthy', 'Pre-Diabetes', 'Hypertension', 'Heart Disease', 'Diabetes']
Length: 5, dtype: str

In [254]:
df.duplicated().sum()

np.int64(0)

In [255]:
df.drop_duplicates(inplace=True)

In [256]:
df.duplicated().sum()

np.int64(0)

In [257]:
df.isnull().sum()

Age                 0
Gender              0
BMI                 0
BloodPressure       0
GlucoseLevel        0
Cholesterol         0
HeartRate           0
Smoking             0
Alcohol             0
PhysicalActivity    0
FamilyHistory       0
Disease             0
dtype: int64

In [258]:
df.drop(['FamilyHistory','Alcohol','PhysicalActivity','Cholesterol','GlucoseLevel'],axis=1,inplace=True)

In [259]:
char=df.select_dtypes(include='object')
num=df.select_dtypes(exclude='object')

C:\Users\abc\AppData\Local\Temp\ipykernel_20092\2102593220.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  char=df.select_dtypes(include='object')

In [260]:
num

      Age   BMI  BloodPressure  HeartRate
0      23  17.5            102         88
1      69  31.1            118         92
2      61  31.3            114         74
3      47  23.9            105         68
4      47  28.3            148         84
...   ...   ...            ...        ...
9995   49  27.1            177         59
9996   84  29.2            142         77
9997   41  22.8            177         71
9998   55  29.0            126         57
9999   59  32.2            151         93

[10000 rows x 4 columns]

In [261]:
char

      Gender Smoking       Disease
0       Male      No       Healthy
1       Male      No  Pre-Diabetes
2     Female     Yes       Healthy
3     Female      No       Healthy
4       Male      No       Healthy
...      ...     ...           ...
9995    Male      No  Hypertension
9996    Male      No  Hypertension
9997    Male      No  Hypertension
9998    Male      No  Pre-Diabetes
9999    Male      No  Pre-Diabetes

[10000 rows x 3 columns]

In [262]:
char['Gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [263]:
Gender_dict={'Male':2, 'Female':3}
char['Gender']=char['Gender'].map(Gender_dict)

In [264]:
char['Smoking'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [265]:
Smoking_dict={'No':0, 'Yes':1}
char['Smoking']=char['Smoking'].map(Smoking_dict)

In [266]:
char['Disease'].unique()

<StringArray>
['Healthy', 'Pre-Diabetes', 'Hypertension', 'Heart Disease', 'Diabetes']
Length: 5, dtype: str

In [267]:
disease_dict={'Healthy':1, 'Pre-Diabetes':2, 'Hypertension':3, 'Heart Disease':4, 'Diabetes':5}
char['Disease']=char['Disease'].map(disease_dict)

In [268]:
char

      Gender  Smoking  Disease
0          2        0        1
1          2        0        2
2          3        1        1
3          3        0        1
4          2        0        1
...      ...      ...      ...
9995       2        0        3
9996       2        0        3
9997       2        0        3
9998       2        0        2
9999       2        0        2

[10000 rows x 3 columns]

In [269]:
char

      Gender  Smoking  Disease
0          2        0        1
1          2        0        2
2          3        1        1
3          3        0        1
4          2        0        1
...      ...      ...      ...
9995       2        0        3
9996       2        0        3
9997       2        0        3
9998       2        0        2
9999       2        0        2

[10000 rows x 3 columns]

In [270]:
total_df=pd.concat([char,num],axis=1)

In [271]:
total_df

      Gender  Smoking  Disease  Age   BMI  BloodPressure  HeartRate
0          2        0        1   23  17.5            102         88
1          2        0        2   69  31.1            118         92
2          3        1        1   61  31.3            114         74
3          3        0        1   47  23.9            105         68
4          2        0        1   47  28.3            148         84
...      ...      ...      ...  ...   ...            ...        ...
9995       2        0        3   49  27.1            177         59
9996       2        0        3   84  29.2            142         77
9997       2        0        3   41  22.8            177         71
9998       2        0        2   55  29.0            126         57
9999       2        0        2   59  32.2            151         93

[10000 rows x 7 columns]

In [272]:
total_df.duplicated().sum()

np.int64(0)

In [273]:
total_df.drop_duplicates(inplace=True)

In [274]:
total_df.isnull().sum()

Gender           0
Smoking          0
Disease          0
Age              0
BMI              0
BloodPressure    0
HeartRate        0
dtype: int64

In [275]:
total_df.to_csv("final1_clen_medical.csv")

In [276]:
x=total_df.drop('Disease',axis=1)

In [277]:
x

      Gender  Smoking  Age   BMI  BloodPressure  HeartRate
0          2        0   23  17.5            102         88
1          2        0   69  31.1            118         92
2          3        1   61  31.3            114         74
3          3        0   47  23.9            105         68
4          2        0   47  28.3            148         84
...      ...      ...  ...   ...            ...        ...
9995       2        0   49  27.1            177         59
9996       2        0   84  29.2            142         77
9997       2        0   41  22.8            177         71
9998       2        0   55  29.0            126         57
9999       2        0   59  32.2            151         93

[10000 rows x 6 columns]

In [278]:
y=total_df[['Disease']]

In [279]:
y

      Disease
0           1
1           2
2           1
3           1
4           1
...       ...
9995        3
9996        3
9997        3
9998        2
9999        2

[10000 rows x 1 columns]

In [280]:
import pandas as pd
import numpy as np
import os
df=pd.read_csv('final1_clen_medical.csv')

In [281]:
df

,Unnamed: 0,Gender,Smoking,Disease,Age,BMI,BloodPressure,HeartRate
0,0,2,0,1,23,17.5,102,88
1,1,2,0,2,69,31.1,118,92
2,2,3,1,1,61,31.3,114,74
3,3,3,0,1,47,23.9,105,68
4,4,2,0,1,47,28.3,148,84
...,...,...,...,...,...,...,...,...
9995,9995,2,0,3,49,27.1,177,59
9996,9996,2,0,3,84,29.2,142,77
9997,9997,2,0,3,41,22.8,177,71
9998,9998,2,0,2,55,29.0,126,57
9999,9999,2,0,2,59,32.2,151,93

In [282]:
healthy_df=df[df['Disease']==1]

In [283]:
healthy_df

,Unnamed: 0,Gender,Smoking,Disease,Age,BMI,BloodPressure,HeartRate
0,0,2,0,1,23,17.5,102,88
2,2,3,1,1,61,31.3,114,74
3,3,3,0,1,47,23.9,105,68
4,4,2,0,1,47,28.3,148,84
5,5,3,0,1,75,25.0,90,59
...,...,...,...,...,...,...,...,...
9985,9985,2,0,1,65,36.1,103,69
9987,9987,2,0,1,41,28.0,164,96
9989,9989,2,0,1,57,23.2,160,99
9993,9993,2,0,1,29,22.1,95,58
9994,9994,3,1,1,82,21.7,153,61

In [284]:
Hypertension_df=df[df['Disease']==2]

In [285]:
Hypertension_df

,Unnamed: 0,Gender,Smoking,Disease,Age,BMI,BloodPressure,HeartRate
1,1,2,0,2,69,31.1,118,92
27,27,3,0,2,73,28.6,176,99
31,31,2,0,2,33,26.0,160,88
37,37,3,0,2,73,24.3,158,56
47,47,3,1,2,77,28.7,101,76
...,...,...,...,...,...,...,...,...
9984,9984,3,0,2,35,31.8,92,59
9990,9990,3,0,2,39,24.2,149,66
9991,9991,2,1,2,32,25.7,172,101
9998,9998,2,0,2,55,29.0,126,57
9999,9999,2,0,2,59,32.2,151,93

In [286]:
Hypertension_Glucose_Level_df=Hypertension_df[Hypertension_df['Gender']==2]

In [287]:
Hypertension_Glucose_Level_df

,Unnamed: 0,Gender,Smoking,Disease,Age,BMI,BloodPressure,HeartRate
1,1,2,0,2,69,31.1,118,92
31,31,2,0,2,33,26.0,160,88
50,50,2,0,2,68,21.2,107,61
59,59,2,1,2,63,19.6,138,60
68,68,2,1,2,23,24.3,167,65
...,...,...,...,...,...,...,...,...
9979,9979,2,1,2,24,29.2,146,92
9982,9982,2,1,2,40,18.9,170,81
9991,9991,2,1,2,32,25.7,172,101
9998,9998,2,0,2,55,29.0,126,57
9999,9999,2,0,2,59,32.2,151,93

In [288]:
j=Hypertension_Glucose_Level_df[Hypertension_Glucose_Level_df['BloodPressure']>40]

In [289]:
j

,Unnamed: 0,Gender,Smoking,Disease,Age,BMI,BloodPressure,HeartRate
1,1,2,0,2,69,31.1,118,92
31,31,2,0,2,33,26.0,160,88
50,50,2,0,2,68,21.2,107,61
59,59,2,1,2,63,19.6,138,60
68,68,2,1,2,23,24.3,167,65
...,...,...,...,...,...,...,...,...
9979,9979,2,1,2,24,29.2,146,92
9982,9982,2,1,2,40,18.9,170,81
9991,9991,2,1,2,32,25.7,172,101
9998,9998,2,0,2,55,29.0,126,57
9999,9999,2,0,2,59,32.2,151,93

In [290]:
Hypertension_Glucose_Level_df[Hypertension_Glucose_Level_df['HeartRate']>40]

,Unnamed: 0,Gender,Smoking,Disease,Age,BMI,BloodPressure,HeartRate
1,1,2,0,2,69,31.1,118,92
31,31,2,0,2,33,26.0,160,88
50,50,2,0,2,68,21.2,107,61
59,59,2,1,2,63,19.6,138,60
68,68,2,1,2,23,24.3,167,65
...,...,...,...,...,...,...,...,...
9979,9979,2,1,2,24,29.2,146,92
9982,9982,2,1,2,40,18.9,170,81
9991,9991,2,1,2,32,25.7,172,101
9998,9998,2,0,2,55,29.0,126,57
9999,9999,2,0,2,59,32.2,151,93

In [291]:
Hypertension_Glucose_Level_df[Hypertension_Glucose_Level_df['BMI']<40]

,Unnamed: 0,Gender,Smoking,Disease,Age,BMI,BloodPressure,HeartRate
1,1,2,0,2,69,31.1,118,92
31,31,2,0,2,33,26.0,160,88
50,50,2,0,2,68,21.2,107,61
59,59,2,1,2,63,19.6,138,60
68,68,2,1,2,23,24.3,167,65
...,...,...,...,...,...,...,...,...
9979,9979,2,1,2,24,29.2,146,92
9982,9982,2,1,2,40,18.9,170,81
9991,9991,2,1,2,32,25.7,172,101
9998,9998,2,0,2,55,29.0,126,57
9999,9999,2,0,2,59,32.2,151,93

In [292]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [293]:
df=pd.read_csv("final1_clen_medical.csv")

In [294]:
df

,Unnamed: 0,Gender,Smoking,Disease,Age,BMI,BloodPressure,HeartRate
0,0,2,0,1,23,17.5,102,88
1,1,2,0,2,69,31.1,118,92
2,2,3,1,1,61,31.3,114,74
3,3,3,0,1,47,23.9,105,68
4,4,2,0,1,47,28.3,148,84
...,...,...,...,...,...,...,...,...
9995,9995,2,0,3,49,27.1,177,59
9996,9996,2,0,3,84,29.2,142,77
9997,9997,2,0,3,41,22.8,177,71
9998,9998,2,0,2,55,29.0,126,57
9999,9999,2,0,2,59,32.2,151,93

In [295]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [296]:
df.duplicated().sum()

np.int64(0)

In [297]:
df.isnull().sum()

Gender           0
Smoking          0
Disease          0
Age              0
BMI              0
BloodPressure    0
HeartRate        0
dtype: int64

In [298]:
df['Disease'].unique()

array([1, 2, 3, 4, 5])

In [299]:
df

      Gender  Smoking  Disease  Age   BMI  BloodPressure  HeartRate
0          2        0        1   23  17.5            102         88
1          2        0        2   69  31.1            118         92
2          3        1        1   61  31.3            114         74
3          3        0        1   47  23.9            105         68
4          2        0        1   47  28.3            148         84
...      ...      ...      ...  ...   ...            ...        ...
9995       2        0        3   49  27.1            177         59
9996       2        0        3   84  29.2            142         77
9997       2        0        3   41  22.8            177         71
9998       2        0        2   55  29.0            126         57
9999       2        0        2   59  32.2            151         93

[10000 rows x 7 columns]

In [300]:
x=df.drop('Disease',axis=1)

In [301]:
x

      Gender  Smoking  Age   BMI  BloodPressure  HeartRate
0          2        0   23  17.5            102         88
1          2        0   69  31.1            118         92
2          3        1   61  31.3            114         74
3          3        0   47  23.9            105         68
4          2        0   47  28.3            148         84
...      ...      ...  ...   ...            ...        ...
9995       2        0   49  27.1            177         59
9996       2        0   84  29.2            142         77
9997       2        0   41  22.8            177         71
9998       2        0   55  29.0            126         57
9999       2        0   59  32.2            151         93

[10000 rows x 6 columns]

In [302]:
y=df[['Disease']]

In [303]:
y

      Disease
0           1
1           2
2           1
3           1
4           1
...       ...
9995        3
9996        3
9997        3
9998        2
9999        2

[10000 rows x 1 columns]

In [304]:
x

      Gender  Smoking  Age   BMI  BloodPressure  HeartRate
0          2        0   23  17.5            102         88
1          2        0   69  31.1            118         92
2          3        1   61  31.3            114         74
3          3        0   47  23.9            105         68
4          2        0   47  28.3            148         84
...      ...      ...  ...   ...            ...        ...
9995       2        0   49  27.1            177         59
9996       2        0   84  29.2            142         77
9997       2        0   41  22.8            177         71
9998       2        0   55  29.0            126         57
9999       2        0   59  32.2            151         93

[10000 rows x 6 columns]

In [305]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [306]:
x_train

      Gender  Smoking  Age   BMI  BloodPressure  HeartRate
9254       2        1   76  29.6            134        101
1561       3        0   35  29.3             96         58
1670       2        0   69  29.6            164         98
6087       2        0   47  29.0            159        109
6669       2        1   42  23.4            107         82
...      ...      ...  ...   ...            ...        ...
5734       3        0   61  30.2            175        102
5191       3        0   79  20.5            150         84
5390       2        0   30  27.6            119        110
860        2        1   82  30.7            108        102
7270       2        0   38  17.3            176         66

[8000 rows x 6 columns]

In [307]:
x_test

      Gender  Smoking  Age   BMI  BloodPressure  HeartRate
6252       2        0   36  23.5            122         99
4684       3        0   52  23.0            147        107
1731       2        0   78  26.3            118         55
4742       2        0   46  22.6            161         59
4521       3        1   64  27.2            126        108
...      ...      ...  ...   ...            ...        ...
6412       3        0   23  25.5            114         99
8285       2        0   20  32.3            131         77
7853       3        0   53  26.8            180         94
1095       3        0   23  35.2            118        100
6929       3        0   68  16.5            105         62

[2000 rows x 6 columns]

In [308]:
y_train

      Disease
9254        3
1561        1
1670        1
6087        1
6669        1
...       ...
5734        2
5191        1
5390        1
860         3
7270        3

[8000 rows x 1 columns]

In [309]:
y_test

      Disease
6252        1
4684        1
1731        1
4742        1
4521        3
...       ...
6412        1
8285        1
7853        3
1095        1
6929        1

[2000 rows x 1 columns]

In [310]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((8000, 6), (2000, 6), (8000, 1), (2000, 1))

# Linear regression model

In [311]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [312]:
pred=lr.predict(x_test)

In [313]:
pred

array([[1.11504794],
       [1.48608303],
       [1.6480236 ],
       ...,
       [1.92929838],
       [1.42694905],
       [1.0249377 ]], shape=(2000, 1))

In [314]:
y_test

      Disease
6252        1
4684        1
1731        1
4742        1
4521        3
...       ...
6412        1
8285        1
7853        3
1095        1
6929        1

[2000 rows x 1 columns]

In [315]:
print("test score",lr.score(x_test,y_test))
print("test score",lr.score(x_train,y_train))

test score 0.2398088019739939
test score 0.19977171653101788

# SVM(svr) model

In [316]:
from sklearn.svm import SVC,SVR
svr=SVR()
svr.fit(x_train,y_train)

c:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR()

In [317]:
print("test score",svr.score(x_test,y_test))
print("train score",svr.score(x_train,y_train))

test score 0.04791718173554038
train score 0.017251904685882335

# SVM(svc) model

In [318]:
from sklearn.svm import SVC
svc=SVR()
svc.fit(x_train,y_train)

c:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR()

In [319]:
print("test score",svc.score(x_test,y_test))
print("train score",svc.score(x_train,y_train))

test score 0.04791718173554038
train score 0.017251904685882335

In [320]:
# import joblib
# joblib.dump(sv,"sv load.lb")

# logistic regression model

In [321]:
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()
log.fit(x_train,y_train)

c:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [322]:
print("log  test score",log.score(x_test,y_test))
print("log  train score",log.score(x_train,y_train))

log  test score 0.6395
log  train score 0.632125

# Decissiontree Classifier model

In [323]:
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [324]:
print("test scoore",dtc.score(x_test,y_test))
print("train scoore",dtc.score(x_train,y_train))

test scoore 0.528
train scoore 1.0

# decissiontree classifier model with parameters

In [325]:
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
dtcwp=DecisionTreeClassifier(criterion='entropy',min_samples_split=3,min_samples_leaf=2)
dtcwp.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2,
                       min_samples_split=3)

In [326]:
print("test scoore",dtcwp.score(x_test,y_test))
print("train scoore",dtcwp.score(x_train,y_train))

test scoore 0.546
train scoore 0.889625

In [327]:
dtcwp.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 2,
 'min_samples_split': 3,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

# decissiontree regressor model

In [328]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor()
dtr.fit(x_train,y_train)

DecisionTreeRegressor()

In [329]:
print("test score",dtr.score(x_test,y_test))
print("train score",dtr.score(x_train,y_train))

test score -0.3095428936859492
train score 1.0

In [330]:
dtr.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

# decissiontree regressor with parameters

In [331]:
from sklearn.tree import DecisionTreeRegressor
dtrwp=DecisionTreeRegressor(criterion='poisson',min_samples_split=3,min_samples_leaf=2)
dtrwp.fit(x_train,y_train)

DecisionTreeRegressor(criterion='poisson', min_samples_leaf=2,
                      min_samples_split=3)

In [332]:
print("test scoore",dtrwp.score(x_test,y_test))
print("test scoore",dtrwp.score(x_train,y_train))

test scoore -0.18050933289402793
test scoore 0.864972854119345

In [333]:
dtrwp.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'poisson',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 2,
 'min_samples_split': 3,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

#  KNN  classifier model

In [334]:
from sklearn.neighbors import KNeighborsClassifier
knnc=KNeighborsClassifier()
knnc.fit(x,y)

c:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neighbors\_classification.py:243: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier()

In [335]:
print("test scoore",knnc.score(x_test,y_test))
print("training scoore",knnc.score(x_train,y_train))

test scoore 0.6985
training scoore 0.683875

# KNN regressor model

In [336]:
from sklearn.neighbors import KNeighborsRegressor
knnr=KNeighborsRegressor()
knnr.fit(x,y)

KNeighborsRegressor()

In [337]:
print("test scoore",knnr.score(x_test,y_test))
print("training scoore",knnr.score(x_train,y_train))

test scoore 0.3851501578814266
training scoore 0.35181803945879364

# Randomforest classifier model

In [338]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(x, y)

c:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier()

In [339]:
print("test scoore",rfc.score(x_test,y_test))
print("test scoore",rfc.score(x_train,y_train))

test scoore 1.0
test scoore 1.0

In [340]:
import joblib
joblib.dump(rfc,"RandomForestClassifier.lb")

['RandomForestClassifier.lb']

# Randomforest regressor model

In [341]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(n_estimators=500)
rfr.fit(x, y)

c:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(n_estimators=500)

In [342]:
print("test scoore",rfr.score(x_test,y_test))
print("test scoore",rfr.score(x_train,y_train))

test scoore 0.8972031778700549
test scoore 0.8929312171977185

# Randomforest regressor model with parameters

In [343]:
from sklearn.ensemble import RandomForestRegressor
rfrwp = RandomForestRegressor(criterion='squared_error',min_samples_split=3,min_samples_leaf=2)
rfrwp.fit(x, y)

c:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(min_samples_leaf=2, min_samples_split=3)

In [344]:
print("test scoore",rfrwp.score(x_test,y_test))
print("test scoore",rfrwp.score(x_train,y_train))

test scoore 0.8056638625050374
test scoore 0.7983975764495553

In [345]:
rfrwp.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': 1.0,
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 2,
 'min_samples_split': 3,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

#  Model train by another data

In [346]:
# from sklearn.datasets import load_breast_cancer
# # sv=SVR()
# # sv.fit(x_train,y_train)
# x,y=load_breast_cancer(return_X_y=True)
# x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
# from sklearn.svm import SVC
# sv=SVR()
# sv.fit(x_train,y_train)
# print("svc training",sv.score(x_test,y_test))
# print("svc training",sv.score(x_train,y_train))
# joblib.dump(sv,"sv_load.lb")
# from sklearn.linear_model import LinearRegression
# log=LinearRegression()
# log.fit(x_train,y_train)
# print("log score",log.score(x_test,y_test))
# print("log score",log.score(x_train,y_train))

# decissiontree classifier with another datase

In [347]:
# #with parameter
# from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
# from sklearn.datasets import load_iris
# x,y=load_iris(return_X_y=True)
# x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
# dt=DecisionTreeClassifier(criterion='entropy',min_samples_split=3,min_samples_leaf=2)
# dt.fit(x_train,y_train)

In [348]:
# print("test scoore",dt.score(x_test,y_test))
# print("training scoore",dt.score(x_train,y_train))

In [349]:
# dt.get_params()

In [350]:
df

      Gender  Smoking  Disease  Age   BMI  BloodPressure  HeartRate
0          2        0        1   23  17.5            102         88
1          2        0        2   69  31.1            118         92
2          3        1        1   61  31.3            114         74
3          3        0        1   47  23.9            105         68
4          2        0        1   47  28.3            148         84
...      ...      ...      ...  ...   ...            ...        ...
9995       2        0        3   49  27.1            177         59
9996       2        0        3   84  29.2            142         77
9997       2        0        3   41  22.8            177         71
9998       2        0        2   55  29.0            126         57
9999       2        0        2   59  32.2            151         93

[10000 rows x 7 columns]

In [351]:
print(x.columns)
print(x.shape)

Index(['Gender', 'Smoking', 'Age', 'BMI', 'BloodPressure', 'HeartRate'], dtype='str')
(10000, 6)

In [352]:
print(rfc.n_features_in_)

6